#debug: true

build:
  image: armdrone/drone-plugin-base
  commands:
    - apk update && apk add tar gzip curl bash
    - export ARCH=armv6l
    - export VERSION=1.21.1
#VERSION=latest
    - export URL=https://busybox.net/downloads/binaries/${VERSION}/busybox-${ARCH}
    - curl -L ${URL} > busybox
# https://github.com/docker/docker/contrib/
    - chmod +x mkimage.sh
    - ./mkimage.sh
    - ls -la

publish:
  docker:
#    load: /drone/src/github.com/firecyberice/arm-alpine/temp.tar
#    environment:
#      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: firecyberice/armhf-busybox
    tag: 
      - latest
      - 1.21.1
